#!/bin/bash

echo "🔄 Vercel 登录修复方案"
echo "======================="
echo ""
echo "方案 1：重新生成登录链接"
echo "------------------------"
echo "在终端按 Ctrl+C 取消当前命令"
echo "然后重新运行：npx vercel login"
echo ""
echo "方案 2：直接在浏览器登录 Vercel"
echo "-------------------------------"
echo "1. 打开浏览器访问：https://vercel.com/login"
echo "2. 点击 'Continue with GitHub'"
echo "3. 使用 5435samwang-bit 账号登录"
echo "4. 登录成功后，返回终端"
echo "5. 运行：npx vercel --prod"
echo ""
echo "方案 3：使用 Vercel 网站直接部署"
echo "--------------------------------"
echo "1. 打开 https://vercel.com/new"
echo "2. 点击 'Import Git Repository'"
echo "3. 选择 GitHub，授权访问"
echo "4. 导入 mc-connects-website 仓库"
echo "5. 点击 Deploy"
echo ""
